const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const {createAccountDeletionService}=require('./account-deletion.cjs');
const msg=overrides=>JSON.stringify({type:'oharu:account:delete',requestId:'qa:1',accessToken:'synthetic-token',password:'synthetic-password',confirmation:'DELETE',...overrides});
test('native deletion strict shape rejects URLs owners oversized passwords and invalid tokens without fetch',async()=>{let calls=0;const service=createAccountDeletionService(async()=>{calls++;throw Error()});for(const raw of [msg({url:'https://evil.invalid'}),msg({user_id:'owner'}),msg({password:'x'.repeat(4097)}),msg({accessToken:'x\r\nInjected:yes'}),msg({confirmation:'delete'}),'null','{}']){const result=await service.handle(raw);assert.equal(result.deleted,false);assert(!JSON.stringify(result).includes('synthetic'));}assert.equal(calls,0);});
test('native deletion fixes endpoint strips headers and never reflects response secrets',async()=>{const service=createAccountDeletionService(async(url,o)=>{assert.equal(url,'https://tcaghsjndfaxlsgaqrdi.supabase.co/functions/v1/delete-account');assert.equal(o.headers.Origin,undefined);assert.equal(o.headers.Authorization,'Bearer synthetic-token');assert.deepEqual(JSON.parse(o.body),{password:'synthetic-password',confirmation:'DELETE'});return {ok:false,status:401,json:async()=>({deleted:false,code:'synthetic-token',password:'synthetic-password'})}});assert.deepEqual(await service.handle(msg()),{requestId:'qa:1',httpStatus:401,deleted:false,code:'delete_failed'});});
test('native deletion times out without logging or echoing the request',async()=>{const service=createAccountDeletionService((url,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(Error('synthetic-password')))),20);assert.deepEqual(await service.handle(msg()),{requestId:'qa:1',httpStatus:504,deleted:false,code:'request_timeout'});});
test('native duplicate/inflight requests issue only one POST',async()=>{let release,calls=0;const service=createAccountDeletionService(async()=>{calls++;await new Promise(r=>release=r);return {ok:true,status:200,json:async()=>({deleted:true})}});const first=service.handle(msg());assert.equal((await service.handle(msg({requestId:'qa:2'}))).httpStatus,409);release();assert.equal((await first).deleted,true);assert.equal((await service.handle(msg())).httpStatus,409);assert.equal(calls,1);});
test('native app routes delete only after exact bundled URL guard and patches retain iframe rejection',()=>{const app=fs.readFileSync(__dirname+'/App.js','utf8');const gate=app.indexOf("event.url.split('#')[0] !== uri");const route=app.indexOf("type === 'oharu:account:delete'");assert(gate>=0&&route>gate);const patch=fs.readFileSync(__dirname+'/patch-webview.cjs','utf8');assert(patch.includes('isMainFrame'));assert(patch.includes('sourceOrigin.toString()'));});

test('native allows exact backend error codes and requires deleted true for any success',async()=>{for(const code of ['deletion_not_enabled','authentication_required','authentication_failed','reauthentication_failed','mfa_reauthentication_unsupported','password_reauthentication_unsupported','storage_verification_required','storage_verification_failed','account_deletion_unconfirmed']){const result=await createAccountDeletionService(async()=>({ok:false,status:503,json:async()=>({deleted:false,code})})).handle(msg());assert.equal(result.code,code);assert.equal(result.deleted,false);}const malformed=await createAccountDeletionService(async()=>({ok:true,status:200,json:async()=>({ok:true})})).handle(msg());assert.equal(malformed.deleted,false);});
