const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {test}=require('node:test');const {chromium}=require('playwright');
async function fixture(run,{width=390,height=744,platform='ios'}={}){const browser=await chromium.launch({headless:true,channel:'chrome'});try{const page=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.ReactNativeWebView={postMessage(){}}});const html=fs.readFileSync(path.join(__dirname,'assets/web/app.html'),'utf8').replace('function restoreIOSRoute(event) {', 'window.__testSetUser = id => { currentUserId=id; }; function restoreIOSRoute(event) {');await page.route('**/*',r=>r.request().resourceType()==='document'?r.fulfill({contentType:'text/html',body:html}):r.abort());await page.goto('http://oharu-ios.test/?mobile=1&nativePlatform='+platform+'&lang=en');await page.waitForFunction(()=>window.__oharuReady);await run(page);assert.deepEqual(errors,[]);}finally{await browser.close()}}
test('iOS settings Back and history swipe equivalent return to selected calendar',()=>fixture(async p=>{await p.locator('#calBtn').click();await p.locator('#nextM').click();const month=await p.locator('#calMonth').textContent();await p.locator('#setBtn').click();await p.locator('#settingsBackBtn').click();await p.locator('#calView').waitFor({state:'visible'});assert.equal(await p.locator('#calMonth').textContent(),month);await p.goBack();await p.locator('#todayView').waitFor({state:'visible'});await p.goForward();await p.locator('#calView').waitFor({state:'visible'});}));
test('iOS login close stays reachable in short viewport and restores settings scroll',()=>fixture(async p=>{await p.locator('#setBtn').click();await p.locator('#setAccount button').click();await p.locator('#email').fill('synthetic@example.invalid');await p.locator('#pw').fill('not-a-real-password');await p.setViewportSize({width:390,height:330});await p.locator('#pw').focus();await p.evaluate(()=>window.dispatchEvent(new Event('oharu:keyboard')));await p.locator('#backLink').click();await p.locator('#setView').waitFor({state:'visible'});assert.equal(await p.locator('#pw').inputValue(),'');assert.equal(await p.evaluate(()=>document.activeElement.id),'iosAccountAction');await p.locator('#setAccount button').click();await p.keyboard.press('Escape');await p.locator('#setView').waitFor({state:'visible'});assert.equal(await p.locator('#backLink').evaluate(e=>e.tagName),'BUTTON');}));
test('iOS small/landscape views keep footer below content and support large text',()=>fixture(async p=>{for(const size of [{width:320,height:568},{width:700,height:320}]){await p.setViewportSize(size);await p.evaluate(()=>document.documentElement.style.setProperty('--ios-font-scale','2'));assert.equal(await p.locator('#input').evaluate(e=>getComputedStyle(e).fontSize),'32px');await p.locator('#setBtn').click();const box=await p.locator('#iosMenu').boundingBox();assert(box.y+box.height<=size.height+1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('#settingsBackBtn').click();}await p.evaluate(()=>document.documentElement.dataset.keyboardOpen='1');assert.equal(await p.locator('#iosMenu').isVisible(),false);await p.evaluate(()=>document.documentElement.dataset.keyboardOpen='0');assert.equal(await p.locator('#iosMenu').isVisible(),true);}));
test('Android keeps prior DOM and does not add route history',()=>fixture(async p=>{assert.equal(await p.locator('#iosMenu').count(),0);const n=await p.evaluate(()=>history.length);await p.locator('#setBtn').click();assert.equal(await p.evaluate(()=>history.length),n);},{platform:'android'}));

test('iOS login interruption preserves long settings scroll and guest draft',()=>fixture(async p=>{await p.locator('#input').fill('Unsubmitted guest draft');await p.locator('#setBtn').click();await p.evaluate(()=>{document.getElementById('iosMainScroll').scrollTop=150;document.getElementById('loginTopBtn').click()});await p.locator('#authView').waitFor({state:'visible'});await p.locator('#backLink').click();await p.locator('#setView').waitFor({state:'visible'});assert.equal(await p.locator('#iosMainScroll').evaluate(e=>e.scrollTop),150);await p.locator('#settingsBackBtn').click();await p.locator('#todayView').waitFor({state:'visible'});assert.equal(await p.locator('#input').inputValue(),'Unsubmitted guest draft');}));

test('iOS history back clears password and restores view; forward remains closable',()=>fixture(async p=>{await p.locator('#setBtn').click();await p.locator('#setAccount button').click();await p.locator('#pw').fill('synthetic-password');await p.goBack();await p.locator('#setView').waitFor({state:'visible'});assert.equal(await p.locator('#pw').inputValue(),'');await p.goForward();await p.locator('#authView').waitFor({state:'visible'});assert.equal(await p.locator('#pw').inputValue(),'');await p.locator('#backLink').click();await p.locator('#setView').waitFor({state:'visible'});}));

test('iOS saved auth route cannot reopen login after authentication; logout makes login accessible',()=>fixture(async p=>{await p.locator('#loginTopBtn').click();await p.locator('#backLink').click();await p.locator('#mainView').waitFor({state:'visible'});await p.evaluate(()=>window.__testSetUser('synthetic-account'));await p.goForward();await p.locator('#mainView').waitFor({state:'visible'});assert.equal(await p.locator('#authView').isVisible(),false);assert.equal(await p.evaluate(()=>JSON.stringify(history.state).includes('synthetic-account')),false);await p.evaluate(()=>window.__testSetUser(null));await p.locator('#loginTopBtn').click();await p.locator('#authView').waitFor({state:'visible'});}));

test('iOS task text time and calendar respond to system text scale without horizontal overflow',()=>fixture(async p=>{await p.locator('#input').fill('Readable synthetic task');await p.locator('#timeInput').fill('23:59');await p.locator('#addBtn').click();await p.evaluate(()=>document.documentElement.style.setProperty('--ios-font-scale','2'));assert.equal(await p.locator('.body .label').evaluate(e=>getComputedStyle(e).fontSize),'31px');assert.equal(await p.locator('.body .time').evaluate(e=>getComputedStyle(e).fontSize),'24px');await p.locator('#calBtn').click();assert.equal(await p.locator('.day .n').first().evaluate(e=>getComputedStyle(e).fontSize),'26px');assert.equal(await p.locator('#iosMainScroll').evaluate(e=>e.scrollWidth<=e.clientWidth),true);},{width:320,height:568}));

test('review F1 calendar title and time survive login close without entering history',()=>fixture(async p=>{await p.locator('#calBtn').click();await p.locator('#nextM').click();await p.locator('.day:not(.other)').nth(9).click();await p.locator('#dayDetail input[type=text]').fill('UNSUBMITTED calendar draft');await p.locator('#dayDetail input[type=time]').fill('16:45');await p.locator('#loginTopBtn').click();await p.locator('#backLink').click();await p.locator('#calView').waitFor({state:'visible'});assert.equal(await p.locator('#dayDetail input[type=text]').inputValue(),'UNSUBMITTED calendar draft');assert.equal(await p.locator('#dayDetail input[type=time]').inputValue(),'16:45');assert.equal(await p.evaluate(()=>JSON.stringify(history.state).includes('UNSUBMITTED')),false);}));
test('review F2 direct history back forward retains live calendar month date and scroll',()=>fixture(async p=>{await p.locator('#calBtn').click();await p.locator('#nextM').click();await p.locator('.day:not(.other)').nth(9).click();await p.evaluate(()=>document.getElementById('iosMainScroll').scrollTop=100);const read=()=>p.evaluate(()=>({month:document.getElementById('calMonth').textContent,date:document.querySelector('.dd-title').textContent,scroll:document.getElementById('iosMainScroll').scrollTop}));const before=await read();await p.goBack();await p.locator('#todayView').waitFor({state:'visible'});await p.goForward();await p.locator('#calView').waitFor({state:'visible'});assert.deepEqual(await read(),before);}));
test('review F3 310 percent short landscape retains readable content and every menu action',()=>fixture(async p=>{await p.locator('#setBtn').click();await p.evaluate(()=>document.documentElement.style.setProperty('--ios-font-scale','3.1'));const m=await p.evaluate(()=>{const s=document.getElementById('iosMainScroll'),menu=document.getElementById('iosMenu'),style=getComputedStyle(s);return {usable:s.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom),menuBottom:menu.getBoundingClientRect().bottom,overflow:document.documentElement.scrollWidth>innerWidth}});assert(m.usable>=80,JSON.stringify(m));assert(m.menuBottom<=241);assert.equal(m.overflow,false);for(const id of ['loginTopBtn','calBtn','setBtn']){await p.locator('#'+id).scrollIntoViewIfNeeded();const r=await p.locator('#'+id).boundingBox();assert(r.y>=0 && r.y+r.height<=241);}}, {width:568,height:240}));

test('calendar draft remains date-specific and successful add clears only submitted draft',()=>fixture(async p=>{await p.locator('#calBtn').click();await p.locator('#nextM').click();await p.locator('.day:not(.other)').nth(9).click();await p.locator('#dayDetail input[type=text]').fill('Date ten draft');await p.locator('#dayDetail input[type=time]').fill('16:45');await p.locator('.day:not(.other)').nth(10).click();assert.equal(await p.locator('#dayDetail input[type=text]').inputValue(),'');await p.locator('#dayDetail input[type=text]').fill('Date eleven draft');await p.locator('.day:not(.other)').nth(9).click();assert.equal(await p.locator('#dayDetail input[type=text]').inputValue(),'Date ten draft');assert.equal(await p.locator('#dayDetail input[type=time]').inputValue(),'16:45');await p.locator('#dayDetail .add').click();assert.equal(await p.locator('#dayDetail input[type=text]').inputValue(),'');assert.equal(await p.locator('#dayDetail input[type=time]').inputValue(),'');assert.equal(await p.locator('#dayDetail .body .label').textContent(),'Date ten draft');await p.locator('.day:not(.other)').nth(10).click();assert.equal(await p.locator('#dayDetail input[type=text]').inputValue(),'Date eleven draft');}));

test('iOS theme detail uses a distinct route and native Back restores settings then calendar',()=>fixture(async p=>{
 await p.locator('#calBtn').click();await p.locator('#nextM').click();const month=await p.locator('#calMonth').textContent();await p.locator('#setBtn').click();const route=await p.evaluate(()=>history.state.routeId);await p.evaluate(()=>{document.getElementById('iosMainScroll').scrollTop=150;document.getElementById('themeSettingsEntry').click()});await p.locator('#themeDetailView').waitFor({state:'visible'});assert.notEqual(await p.evaluate(()=>history.state.routeId),route);assert.equal(await p.locator('#settingsTitle').textContent(),'Theme settings');assert.equal(await p.locator('#themeSettingsBack').isVisible(),false);await p.locator('#themeAITab').click();await p.locator('#oharu-theme-mood').fill('Unsaved theme mood');await p.locator('#settingsBackBtn').click();await p.locator('#setAIConnections').waitFor({state:'visible'});assert.equal(await p.locator('#iosMainScroll').evaluate(e=>e.scrollTop),150);assert.equal(await p.locator('#settingsTitle').textContent(),'Settings');await p.goForward();await p.locator('#themeDetailView').waitFor({state:'visible'});assert.equal(await p.locator('#oharu-theme-mood').inputValue(),'Unsaved theme mood');assert.equal(await p.evaluate(()=>JSON.stringify(history.state).includes('Unsaved')),false);await p.goBack();await p.locator('#setAIConnections').waitFor({state:'visible'});await p.locator('#settingsBackBtn').click();await p.locator('#calView').waitFor({state:'visible'});assert.equal(await p.locator('#calMonth').textContent(),month);
}));

test('iOS theme detail survives login interruption and preserves its input and scroll',()=>fixture(async p=>{
 await p.locator('#setBtn').click();await p.locator('#themeSettingsEntry').click();await p.locator('#themeAITab').click();await p.locator('#oharu-theme-json').fill('{"pending":"theme draft"}');await p.evaluate(()=>{document.getElementById('iosMainScroll').scrollTop=120;document.getElementById('loginTopBtn').click()});await p.locator('#authView').waitFor({state:'visible'});await p.locator('#pw').fill('synthetic-password');await p.locator('#backLink').click();await p.locator('#themeDetailView').waitFor({state:'visible'});assert.equal(await p.locator('#oharu-theme-json').inputValue(),'{"pending":"theme draft"}');assert.equal(await p.locator('#iosMainScroll').evaluate(e=>e.scrollTop),120);assert.equal(await p.locator('#pw').inputValue(),'');assert.equal(await p.locator('#settingsTitle').textContent(),'Theme settings');
}));
