const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {test}=require('node:test');const {chromium}=require('playwright');
const root=path.join(__dirname,'..');
async function fixture(run){const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const context=await browser.newContext({viewport:{width:390,height:844}});
 let html=fs.readFileSync(path.join(root,'web/index.html'),'utf8').replace(/const SUPABASE_URL = .*?;/,'const SUPABASE_URL = "";').replace(/const SUPABASE_ANON_KEY = .*?;/,'const SUPABASE_ANON_KEY = "";');
 html=html.replace('function renderAccount(email) {','window.__settingsAccount=()=>{currentUserId="synthetic-account";renderAccount("synthetic@example.invalid");};\nfunction renderAccount(email) {');
 await context.route('**/*',route=>{const name=new URL(route.request().url()).pathname.slice(1);if(route.request().resourceType()==='document')return route.fulfill({contentType:'text/html',body:html});if(/^[a-z-]+\.(js|css)$/.test(name)&&fs.existsSync(path.join(root,'web',name)))return route.fulfill({path:path.join(root,'web',name)});return route.abort();});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://settings.test/?lang=en');await page.locator('#mainView').waitFor({state:'visible'});await page.locator('#setBtn').click();await run(page);assert.deepEqual(errors,[]);
 }finally{await browser.close();}}
test('provider navigation remains preparing; advanced token controls start closed',()=>fixture(async page=>{
 assert.equal(await page.locator('.settings-advanced').evaluate(e=>e.open),false);
 assert.equal(await page.locator('#mcpRows').isVisible(),false);
 await page.locator('[data-provider=chatgpt]').click();assert.equal(await page.evaluate(()=>OharuSettings.connectionState('chatgpt')),'preparing');assert.match(await page.locator('.ai-connection-guide').textContent(),/in preparation/);assert.equal(await page.locator('.ai-connection-guide a').count(),0);
 assert.equal(await page.locator('.ai-connection-guide button').isDisabled(),true);assert.equal(await page.locator('#themeDetailView').isVisible(),false);assert.doesNotMatch(await page.locator('.ai-connection-guide').textContent(),/theme/i);assert.match(await page.locator('#setAIConnections .settings-note').first().textContent(),/read and add tasks/);assert.match(await page.locator('#setAIConnections .settings-note').first().textContent(),/separate permission/);
 await page.locator('[data-provider=claude]').click();const url=new URL(await page.locator('.ai-connection-guide a').getAttribute('href'));assert.equal(url.origin,'https://claude.ai');assert.equal(url.searchParams.get('connectorName'),'Oharu');assert.equal(url.searchParams.get('connectorUrl'),'https://tcaghsjndfaxlsgaqrdi.supabase.co/functions/v1/mcp');assert.equal(await page.evaluate(()=>OharuSettings.connectionState('claude')),'preparing');
}));
test('gallery uses loaded images; preview is separate from apply and stale input invalidates it',()=>fixture(async page=>{
 assert.equal(await page.locator('#setThemes details').count(),0);assert.equal(await page.locator('.theme-card').first().isVisible(),false);await page.locator('#themeSettingsEntry').click();assert.equal(await page.locator('#setAIConnections').isVisible(),false);assert.equal(await page.locator('.theme-card').count(),10);await page.waitForFunction(()=>[...document.querySelectorAll('.theme-card img')].every(img=>img.complete&&img.naturalWidth>0));
 await page.locator('[data-theme-id=forest]').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.oharuTheme),undefined);await page.locator('[data-action=confirm]').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.oharuTheme),'forest');
 await page.locator('[data-action=undo]').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.oharuTheme),undefined);
 await page.locator('#themeAITab').click();await page.locator('textarea').fill(await page.evaluate(()=>JSON.stringify(OharuThemes.exportTheme())));await page.locator('[data-action=import]').click();assert.equal(await page.locator('[data-action=confirm]').isVisible(),true);await page.locator('textarea').fill('{"script":"alert(1)"}');assert.equal(await page.locator('[data-action=confirm]').isVisible(),false);await page.locator('[data-action=import]').click();assert.match(await page.locator('.oharu-theme-status').textContent(),/Not applied/);assert.equal(await page.evaluate(()=>document.documentElement.dataset.oharuTheme),undefined);
 const legacy=await page.evaluate(()=>{const t=OharuThemes.exportTheme();t.name='Legacy dark file';Object.assign(t.tokens,{bg:'#000000',card:'#000000',soft:'#000000',line:'#000000',dangerSoft:'#000000',text:'#FFFFFF',muted:'#BBBBBB',accent:'#757575',danger:'#F04452'});return JSON.stringify(t);});await page.locator('textarea').fill(legacy);await page.locator('[data-action=import]').click();assert.equal(await page.locator('[data-action=confirm]').isVisible(),true);assert.equal(await page.locator('.theme-preview-name').textContent(),'Legacy dark file');assert.equal(await page.evaluate(()=>document.documentElement.dataset.oharuTheme),undefined);assert.equal(await page.locator('.oharu-theme-sample').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');
}));

test('theme Back preserves settings scroll, accordion state and AI input; history Forward restores detail',()=>fixture(async page=>{
 await page.locator('.settings-advanced').evaluate(e=>e.open=true);await page.evaluate(()=>{scrollTo(0,150);document.getElementById('themeSettingsEntry').click()});await page.locator('#themeDetailView').waitFor({state:'visible'});await page.locator('#themeGalleryTab').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#themeAITab').getAttribute('aria-selected'),'true');await page.locator('#oharu-theme-mood').fill('A calm bookshop');await page.locator('#oharu-theme-json').fill('{"draft":"unfinished"}');await page.locator('#themeSettingsBack').click();await page.locator('#setAIConnections').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>scrollY),150);assert.equal(await page.locator('.settings-advanced').evaluate(e=>e.open),true);assert.equal(await page.locator('#themeSettingsEntry').getAttribute('aria-expanded'),'false');
 await page.goForward();await page.locator('#themeDetailView').waitFor({state:'visible'});assert.equal(await page.locator('#oharu-theme-mood').inputValue(),'A calm bookshop');assert.equal(await page.locator('#oharu-theme-json').inputValue(),'{"draft":"unfinished"}');assert.equal(await page.evaluate(()=>JSON.stringify(history.state).includes('unfinished')),false);await page.keyboard.press('Escape');await page.locator('#setAIConnections').waitFor({state:'visible'});
}));
test('account management stays last with visible deletion; reminder descriptions share padding and English limitations',()=>fixture(async page=>{
 await page.evaluate(()=>__settingsAccount());assert.equal(await page.locator('#setView').evaluate(e=>e.lastElementChild.id),'setAccountManagement');assert.equal(await page.locator('#deleteAccountBtn').isVisible(),true);
 const padding=await page.evaluate(()=>{const title=document.getElementById('reminderTitle').getBoundingClientRect(),status=document.getElementById('reminderStatus').getBoundingClientRect(),description=document.getElementById('reminderCapability').getBoundingClientRect();return {title:title.left+parseFloat(getComputedStyle(document.getElementById('reminderTitle')).paddingLeft),status:status.left,description:description.left+parseFloat(getComputedStyle(document.getElementById('reminderCapability')).paddingLeft)}});assert.equal(padding.status,padding.title);assert.equal(padding.description,padding.title);
 assert.match(await page.locator('#reminderCapability').textContent(),/browser is closed/);await page.locator('#reminderDetailTitle').click();assert.match(await page.locator('#reminderDetail').textContent(),/5 minutes/);assert.match(await page.locator('#reminderDetail').textContent(),/Focus mode/);
}));
